[package]
name = "kommon"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.196", features = ["derive"] } # A generic serialization/deserialization framework

[dev-dependencies]
serde_json = {version = "1.0.113"}